export const DELETE_CARD = 'DELETE_CARD'
export const ADD_CARD = 'ADD_CARD'
export const COLOR_FILTER = 'COLOR_FILTER'
export const ON_SEARCH_CHANGE = 'ON_SEARCH_CHANGE'
export const GET_CARDS = 'GET_CARDS'
export const SEARCH_CARD = 'SEARCH_CARD'
export const CHANGE_COLOR = 'CHANGE_COLOR'
export const NEW_COLOR = 'NEW_COLOR'
